<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitabe084a26ffb1d06c0e814ea4c33cf8c
{
    public static $files = array (
        'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stevenmaguire\\OAuth2\\Client\\' => 28,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
            'Microsoft\\Graph\\Test\\' => 21,
            'Microsoft\\Graph\\' => 16,
        ),
        'L' => 
        array (
            'League\\OAuth2\\Client\\' => 21,
        ),
        'K' => 
        array (
            'Kunnu\\OneDrive\\' => 15,
            'Krizalys\\Onedrive\\' => 18,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stevenmaguire\\OAuth2\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/stevenmaguire/oauth2-microsoft/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'Microsoft\\Graph\\Test\\' => 
        array (
            0 => __DIR__ . '/..' . '/microsoft/microsoft-graph/tests/Functional',
        ),
        'Microsoft\\Graph\\' => 
        array (
            0 => __DIR__ . '/..' . '/microsoft/microsoft-graph/src',
        ),
        'League\\OAuth2\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/oauth2-client/src',
        ),
        'Kunnu\\OneDrive\\' => 
        array (
            0 => __DIR__ . '/..' . '/kunalvarma05/onedrive-client/src/OneDrive',
        ),
        'Krizalys\\Onedrive\\' => 
        array (
            0 => __DIR__ . '/..' . '/krizalys/onedrive-php-sdk/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitabe084a26ffb1d06c0e814ea4c33cf8c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitabe084a26ffb1d06c0e814ea4c33cf8c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
